name: run python script on schedule
on:
  schedule: 
    - cron: '51 13 * * *'
  workflow_dispatch:

jobs:
  extract-bike-points:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python bike_point_extract.py
    
  
